apiVersion: v2
name: portfolio-helm-metallb
description: A Helm chart for deploying metallb configuration
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: metallb
    version: 0.15.2
    repository: https://metallb.github.io/metallb